version: 2.1

jobs:
  test:
    docker:
      - image: image: cimg/openjdk:11.0-browsers
    resource_class: medium
    steps:
      - run: |
          sudo sh -c "curl -s https://swupdate.openvpn.net/repos/repo-public.gpg | apt-key add -"
          sudo sh -c 'echo "deb http://build.openvpn.net/debian/openvpn/stable $(lsb_release -c | cut -f2) main" > /etc/apt/sources.list.d/openvpn-aptrepo.list'
      - run: |    
          sudo apt-get -q -y update
          sudo apt-get -q -y install openvpn resolvconf
          

workflows:
  test:
    jobs:
      - test
